networks:
  hydranet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

services:
  #shell:
    #image: cardanosolutions/cardano-node-ogmios:latest
    #user: $MY_UID:$MY_GID
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true
    #volumes:
      #- ${DEVNET_ROOT}/runtime:/runtime
      #- ${CARDANO_ASSETS_PATH}:/assets

  cardano-cli:
    image: cardanosolutions/cardano-node-ogmios:v6.9.0_10.1.2
    user: $MY_UID:$MY_GID
    entrypoint: /usr/local/bin/cardano-cli
    volumes:
      - ${PWD}:/work
      - ${DEVNET_ROOT}/runtime:/runtime
      - ${CARDANO_ASSETS_PATH}:/assets
    working_dir: /work
    environment:
      - CARDANO_NODE_SOCKET_PATH=/runtime/ipc/node.socket
      - CARDANO_NODE_NETWORK_ID=42

  cardano-node:
    image: cardanosolutions/cardano-node-ogmios:v6.9.0_10.1.2
    container_name: devnet-cardano-node
    user: $MY_UID:$MY_GID
    entrypoint: /usr/local/bin/cardano-node
    environment:
      - CARDANO_BLOCK_PRODUCER=true
      - CARDANO_NODE_NETWORK_ID=42
    # override health check because we're not running ogmios here
    healthcheck:
      test: echo "healthy"
      interval: 1m
    command: [
      "run",
      "--config", "/runtime/chain/cardano-node.json",
      "--topology", "/runtime/chain/topology.json",
      "--database-path", "/runtime/data",
      "--socket-path", "/runtime/ipc/node.socket",
      "--shelley-operational-certificate", "/runtime/chain/opcert.cert",
      "--shelley-kes-key", "/runtime/chain/kes.skey",
      "--shelley-vrf-key", "/runtime/chain/vrf.skey"
    ]
    volumes:
      - ${DEVNET_ROOT}/runtime:/runtime
    restart: on-failure

  ogmios:
    image: cardanosolutions/cardano-node-ogmios:v6.9.0_10.1.2
    container_name: devnet-ogmios
    user: $MY_UID:$MY_GID
    entrypoint: /bin/ogmios
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/runtime/ipc/node.socket",
      "--node-config", "/runtime/chain/cardano-node.json"
    ]
    volumes:
      - ${DEVNET_ROOT}/runtime:/runtime
    ports:
      - ${OGMIOS_PORT:-1337}:1337

  hydra-node:
    image: ghcr.io/cardano-scaling/hydra-node:latest
    user: $MY_UID:$MY_GID
    volumes:
      - ${PWD}:/work
      - ${DEVNET_ROOT}/runtime:/runtime
      - ${DEVNET_ROOT}/hydra:/hydra
      - ${CARDANO_ASSETS_PATH}:/assets
    networks:
      hydranet:
        ipv4_address: ${HYDRA_IP}
    working_dir: /work
    environment:
      - CARDANO_NODE_SOCKET_PATH=/runtime/ipc/node.socket
      - CARDANO_NODE_NETWORK_ID=42

  hydra-tui:
    image: ghcr.io/cardano-scaling/hydra-tui:latest
    user: $MY_UID:$MY_GID
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/work
      - ${DEVNET_ROOT}/runtime:/runtime
      - ${DEVNET_ROOT}/hydra:/hydra
      - ${CARDANO_ASSETS_PATH}:/assets
    networks:
      - hydranet
    working_dir: /work
    environment:
      - CARDANO_NODE_SOCKET_PATH=/runtime/ipc/node.socket
      - CARDANO_NODE_NETWORK_ID=42

