services:
  #shell:
    #image: cardanosolutions/cardano-node-ogmios:latest
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true

  cardano-cli:
    image: cardanosolutions/cardano-node-ogmios:latest
    entrypoint: /usr/local/bin/cardano-cli
    stdin_open: true
    tty: true
    volumes:
      - ${DEVNET_ROOT}:/devnet
        ${KEYS_PATH}:/keys
    environment:
      - CARDANO_NODE_SOCKET_PATH=/devnet/runtime/ipc/node.socket
      - CARDANO_NODE_NETWORK_ID=42

  cardano-node:
    image: cardanosolutions/cardano-node-ogmios:latest
    entrypoint: /usr/local/bin/cardano-node
    environment:
      - CARDANO_BLOCK_PRODUCER=true
      - CARDANO_NODE_SOCKET_PATH=/devnet/runtime/ipc/node.socket
      - CARDANO_NODE_NETWORK_ID=42
    command: [
      "run",
      "--config", "/config/cardano-node.json",
      "--topology", "/config/topology.json",
      "--database-path", "/data",
      "--socket-path", "/ipc/node.socket",
      "--shelley-operational-certificate", "/config/opcert.cert",
      "--shelley-kes-key", "/config/kes.skey",
      "--shelley-vrf-key", "/config/vrf.skey"
    ]
    volumes:
      - ./runtime/chain:/config
      - ./runtime/ipc:/ipc
      - ./runtime/db:/data
    restart: on-failure

  ogmios:
    image: cardanosolutions/cardano-node-ogmios:latest
    entrypoint: /bin/ogmios
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node.json"
    ]
    volumes:
      - ./runtime/chain:/config
      - ./runtime/ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337

