version: "3.5"

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:8.9.2
    environment:
      - CARDANO_BLOCK_PRODUCER=true
    command: [
      "run",
      "--config", "/config/cardano-node.json",
      "--topology", "/config/topology.json",
      "--database-path", "/data",
      "--socket-path", "/ipc/node.socket",
      "--shelley-operational-certificate", "/config/opcert.cert",
      "--shelley-kes-key", "/config/kes.skey",
      "--shelley-vrf-key", "/config/vrf.skey"
    ]
    volumes:
      - ./runtime/chain:/config
      - ./runtime/ipc:/ipc
      - ./runtime/db:/data
    restart: on-failure

  ogmios:
    image: cardanosolutions/ogmios:latest
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node.json"
    ]
    volumes:
      - ./runtime/chain:/config
      - ./runtime/ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337

