#!/usr/bin/env bash

# Based on demo/prepare-devnet.sh script from hydra repo. Added in block time customization
# and auto-startup for cardano-node.  ogmios is started to provide syncronization and
# mempool monitoring.
# Hydra repo: https://github.com/input-output-hk/hydra

# Prepare a "chain" directory holding credentials, a dummy topology and
# "up-to-date" genesis files. If the directory exists, it is wiped out.
set -em

if [[ ! $1 == ?(-)+([0-9]) ]]; then
    SCRIPTNAME=$(basename $0)
    echo "usage: $SCRIPTNAME <block time>"
    exit -1
fi

BASEDIR="$DEVNET_ROOT"
RUNTIMEDIR="$BASEDIR/runtime"
TARGETDIR="$RUNTIMEDIR/chain"

[ -d "$TARGETDIR" ] && { echo "Cleaning up directory $TARGETDIR" ; sudo rm -r $TARGETDIR ; }
mkdir -p "$TARGETDIR"

cp "$BASEDIR"/config/genesis/* "$TARGETDIR"
cp "$BASEDIR"/config/protocol-parameters.json "$TARGETDIR"

# Copy faucet keys, address to the CARDANO_CLI_GURU assets directory
if [[ -v CARDANO_CLI_GURU ]]; then
    echo "Copying faucet keys into CARDANO_CLI_GURU assets directory"
    cp $BASEDIR/config/credentials/faucet.vkey $CARDANO_CLI_GURU/assets/keys
    cp $BASEDIR/config/credentials/faucet.skey $CARDANO_CLI_GURU/assets/keys
    cp $BASEDIR/config/credentials/faucet.addr $CARDANO_CLI_GURU/assets/addr
fi

# Update start time params
echo '{"Producers": []}' > "$TARGETDIR/topology.json"
sed -i "s/\"startTime\": [0-9]*/\"startTime\": $(date +%s)/" "$TARGETDIR/genesis-byron.json" && \
sed -i "s/\"systemStart\": \".*\"/\"systemStart\": \"$(date -u +%FT%TZ)\"/" "$TARGETDIR/genesis-shelley.json"

# Calculate activeSlotsCoeff from slot time parameter and add to genesis file
COEFF=$(jq -n 1/$1)
echo "Setting slot time to $1: coeffecient=$COEFF"
sed -i "s/\"activeSlotsCoeff\": .*/\"activeSlotsCoeff\": $COEFF,/" "$TARGETDIR/genesis-shelley.json"

# Recalculate genesis hashes
BYRON_HASH=$(cardano-cli byron genesis print-genesis-hash --genesis-json $TARGETDIR/genesis-byron.json)
echo "Computed Byron hash: $BYRON_HASH"
sed -i "s/\"ByronGenesisHash\": .*/\"ByronGenesisHash\": \"$BYRON_HASH\",/" "$TARGETDIR/cardano-node.json"
SHELLEY_HASH=$(cardano-cli genesis hash --genesis $TARGETDIR/genesis-shelley.json)
echo "Computed Shelley hash: $SHELLEY_HASH"
sed -i "s/\"ShelleyGenesisHash\": .*/\"ShelleyGenesisHash\": \"$SHELLEY_HASH\",/" "$TARGETDIR/cardano-node.json"
ALONZO_HASH=$(cardano-cli genesis hash --genesis $TARGETDIR/genesis-alonzo.json)
echo "Computed Alonzo hash: $ALONZO_HASH"
sed -i "s/\"AlonzoGenesisHash\": .*/\"AlonzoGenesisHash\": \"$ALONZO_HASH\",/" "$TARGETDIR/cardano-node.json"
CONWAY_HASH=$(cardano-cli genesis hash --genesis $TARGETDIR/genesis-conway.json)
echo "Computed Conway hash: $CONWAY_HASH"
sed -i "s/\"ConwayGenesisHash\": .*/\"ConwayGenesisHash\": \"$CONWAY_HASH\",/" "$TARGETDIR/cardano-node.json"

find $TARGETDIR -type f -exec chmod 0400 {} \;
echo "Prepared devnet"
