#!/bin/bash

# This script acts as a front end for hydra-tui. If it finds an actual hydra-tui binary
# outside this directory in the PATH, it will invoke that binary with the supplied arguments.
# If it doesn't find a hydra-tui binary, it will run hydra-tui in a docker container,
# mounting the appropriate volumes and setting the proper environment variables.

unset hydrapath
for i in $(echo "$PATH" | sed 's/:/ /g'); do 
  if [[ $i != ${DEVNET_ROOT}* ]]; then
    if [ -x $i/hydra-tui ]; then
      hydrapath=$i
      break
    fi
  fi
done

newargs=()
for i in "${@:1}"; do
  tmp=$i
  if [[ $i == ${DEVNET_ROOT}* ]]; then
    tmp=("${i#$DEVNET_ROOT}")
  fi
  if [[ $i == ${CARDANO_CLI_GURU}* ]]; then
    tmp=("${tmp#$CARDANO_CLI_GURU}")
  fi
  newargs+=("${tmp}")
done

#echo "${newargs[*]}"

if [ -z ${hydrapath+x} ]; then
  # hydra-tui not in PATH external to this directory
  docker compose -f $DEVNET_ROOT/docker-compose.yml run --rm hydra-tui "${newargs[@]}"
else 
  $hydrapath/hydra-tui "${@:1}"
fi
