name = "cryptophonic/counter"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'cryptophonic/counter'"

[repository]
user = "cryptophonic"
project = "counter"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
